# faster builds on new travis setup not using sudo
language: php

services:
  - mysql

php:
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer self-update && composer --version

before_script:
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version
            
  # initialize database
  - mysql -e "create database yii2_roa_test"

script:
  - composer deploy-tests
  - composer run-tests
